export type ProductCategory =
    | "AI Tools"
    | "Design"
    | "Video"
    | "Productivity"
    | "Learning"
    | "Business";

export interface Product {
    id: string;
    slug: string;
    name: string;
    duration: string;
    priceInr: number;
    category: ProductCategory;
    bestFor: string;
    shortDescription: string;
    thumbnail: { url: string; alt: string };
    imageAttribution?: string;
    logoUrl?: string | null;
    canUseInAppUI?: boolean;
    brandNotes?: string;
    officialWebsite?: string;
    uses?: string[];
    features?: string[];
}

const images = {
    ai: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80",
    design: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    video: "https://images.unsplash.com/photo-1574717432707-c25419be1f87?auto=format&fit=crop&w=800&q=80",
    productivity: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=800&q=80",
    learning: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80",
    business: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    code: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    abstract: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?auto=format&fit=crop&w=800&q=80"
};

export const products: Product[] = [
    {
        id: "beautiful-ai-1y",
        slug: "beautiful-ai-1y",
        name: "Beautiful AI",
        duration: "1 year",
        priceInr: 899,
        category: "AI Tools",
        bestFor: "Presentations and pitch decks",
        shortDescription: "Create clean, AI‑powered presentations in minutes.",
        thumbnail: { url: images.ai, alt: "AI presentation interface" },
        logoUrl: "/logos/beautiful-ai.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.beautiful.ai",
        uses: ["Pitch Decks", "Marketing Reports", "Sales Proposals", "Educational Slides"],
        features: ["Smart Slide Templates", "Auto-formatting", "Brand Consistency", "Millions of Stock Photos"]
    },
    {
        id: "perplexity-pro-1y",
        slug: "perplexity-pro-1y",
        name: "Perplexity Pro",
        duration: "1 year",
        priceInr: 799,
        category: "AI Tools",
        bestFor: "Research and Q&A",
        shortDescription: "Fast AI search and research assistant for daily work.",
        thumbnail: { url: images.ai, alt: "AI search interface" },
        logoUrl: "/logos/perplexity.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.perplexity.ai",
        uses: ["Academic Research", "Fact Checking", "Coding Assistance", "Daily Information"],
        features: ["Real-time Web Search", "Source Citations", "Copilot Mode", "File Upload Analysis"]
    },
    {
        id: "chatgpt-plus-1m",
        slug: "chatgpt-plus-1m",
        name: "ChatGPT Plus",
        duration: "1 month",
        priceInr: 449,
        category: "AI Tools",
        bestFor: "Chat, coding, content",
        shortDescription: "Access premium AI models for writing, coding and more.",
        thumbnail: { url: images.ai, alt: "AI chat interface" },
        logoUrl: "/logos/chatgpt.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://openai.com",
        uses: ["Content Writing", "Coding & Debugging", "Language Translation", "Creative Brainstorming"],
        features: ["GPT-4 Access", "DALL·E 3 Image Generation", "Advanced Data Analysis", "Browsing Capability"]
    },
    {
        id: "autodesk-1y",
        slug: "autodesk-1y",
        name: "Autodesk",
        duration: "1 year",
        priceInr: 899,
        category: "Design",
        bestFor: "3D modeling and CAD",
        shortDescription: "Professional 3D design and engineering software.",
        thumbnail: { url: images.design, alt: "3D wireframe design" },
        logoUrl: "/logos/autodesk.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.autodesk.com",
        uses: ["3D Modeling", "Architectural Design", "Engineering Simulation", "Animation"],
        features: ["AutoCAD Access", "Revit & Maya", "Cloud Rendering", "Collaboration Tools"]
    },
    {
        id: "ilovepdf-1y",
        slug: "ilovepdf-1y",
        name: "iLovePDF + IMG",
        duration: "1 year",
        priceInr: 299,
        category: "Productivity",
        bestFor: "Document management",
        shortDescription: "Complete PDF and image tools for productivity.",
        thumbnail: { url: images.productivity, alt: "Document workflow" },
        logoUrl: "/logos/ilovepdf.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.ilovepdf.com",
        uses: ["PDF Conversion", "Merging & Splitting", "Compressing PDFs", "Signing Documents"],
        features: ["OCR Technology", "Batch Processing", "Secure Encryption", "Mobile App Access"]
    },
    {
        id: "adobe-creative-cloud-4m",
        slug: "adobe-creative-cloud-4m",
        name: "Adobe Creative Cloud",
        duration: "4 months",
        priceInr: 599,
        category: "Design",
        bestFor: "Students and new creators",
        shortDescription: "Short‑term access to full Adobe Creative Cloud suite.",
        thumbnail: { url: images.design, alt: "Creative design tools" },
        logoUrl: "/logos/adobe-creative-cloud.jpg",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.adobe.com/creativecloud.html",
        uses: ["Graphic Design", "Video Editing", "Photography", "UX/UI Design"],
        features: ["20+ Apps (Photoshop, Illustrator)", "Adobe Fonts", "Cloud Storage", "Behance Integration"]
    },
    {
        id: "adobe-creative-cloud-1y",
        slug: "adobe-creative-cloud-1y",
        name: "Adobe Creative Cloud",
        duration: "1 year",
        priceInr: 1999,
        category: "Design",
        bestFor: "Full‑time designers and agencies",
        shortDescription: "Annual access to 20+ Adobe apps like Photoshop and AE.",
        thumbnail: { url: images.design, alt: "Digital art workspace" },
        logoUrl: "/logos/adobe-creative-cloud.jpg",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.adobe.com/creativecloud.html",
        uses: ["Graphic Design", "Video Editing", "Photography", "UX/UI Design"],
        features: ["20+ Apps (Photoshop, Illustrator)", "Adobe Fonts", "Cloud Storage", "Behance Integration"]
    },
    {
        id: "coursera-1y",
        slug: "coursera-1y",
        name: "Coursera",
        duration: "1 year",
        priceInr: 749,
        category: "Learning",
        bestFor: "Upskilling and certifications",
        shortDescription: "Learn from top universities and companies online.",
        thumbnail: { url: images.learning, alt: "Online learning" },
        logoUrl: "/logos/coursera.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.coursera.org",
        uses: ["Professional Certificates", "Degree Programs", "Skill Acquisition", "Career Advancement"],
        features: ["Top University Partners", "Flexible Learning", "Offline Mode", "Verified Certificates"]
    },
    {
        id: "granola-business-1y",
        slug: "granola-business-1y",
        name: "Granola Business",
        duration: "1 year",
        priceInr: 599,
        category: "Business",
        bestFor: "Meeting intelligence",
        shortDescription: "AI notepad for meetings that organizes your notes.",
        thumbnail: { url: images.business, alt: "Meeting analytics" },
        logoUrl: "/logos/granola.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://granola.so",
        uses: ["Meeting Notes", "Action Item Tracking", "Team Alignment", "Interview Recaps"],
        features: ["AI Summaries", "Custom Templates", "Shareable Links", "Calendar Integration"]
    },
    {
        id: "linear-business-1y",
        slug: "linear-business-1y",
        name: "Linear Business",
        duration: "1 year",
        priceInr: 699,
        category: "Business",
        bestFor: "Product teams",
        shortDescription: "Streamlined issue tracking and product roadmaps.",
        thumbnail: { url: images.business, alt: "Project roadmap" },
        logoUrl: "/logos/linear.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://linear.app",
        uses: ["Issue Tracking", "Sprint Planning", "Product Roadmaps", "Bug Reporting"],
        features: ["Keyboard-First Design", "Git Integration", "Automated Workflows", "Real-time Sync"]
    },
    {
        id: "superhuman-starter-1y",
        slug: "superhuman-starter-1y",
        name: "Superhuman Starter",
        duration: "1 year",
        priceInr: 499,
        category: "Productivity",
        bestFor: "Email power users",
        shortDescription: "The fastest email experience ever made.",
        thumbnail: { url: images.productivity, alt: "Email inbox" },
        logoUrl: "/logos/superhuman.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://superhuman.com",
        uses: ["Email Efficiency", "Inbox Zero", "Sales Outreach", "Team Communication"],
        features: ["Split Inbox", "AI Composing", "Read Statuses", "Undo Send"]
    },
    {
        id: "notion-6m",
        slug: "notion-6m",
        name: "Notion",
        duration: "6 months",
        priceInr: 299,
        category: "Productivity",
        bestFor: "Notes, wikis, task management",
        shortDescription: "All‑in‑one workspace for docs, tasks and databases.",
        thumbnail: { url: images.productivity, alt: "Notion workspace" },
        logoUrl: "/logos/notion.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.notion.so",
        uses: ["Knowledge Management", "Project Tracking", "Documentation", "Personal Organization"],
        features: ["Custom Databases", "AI Writer", "Team Spaces", "Template Gallery"]
    },
    {
        id: "raycast-pro-1y",
        slug: "raycast-pro-1y",
        name: "Raycast Pro",
        duration: "1 year",
        priceInr: 449,
        category: "Productivity",
        bestFor: "Mac power users",
        shortDescription: "Supercharge your Mac with a fast command bar launcher.",
        thumbnail: { url: images.code, alt: "Command palette" },
        logoUrl: "/logos/raycast.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.raycast.com",
        uses: ["System Control", "Clipboard History", "Window Management", "Script Execution"],
        features: ["AI Chat", "Custom Extensions", "Cloud Sync", "Themes"]
    },
    {
        id: "chatprd-pro-1y",
        slug: "chatprd-pro-1y",
        name: "ChatPRD Pro",
        duration: "1 year",
        priceInr: 599,
        category: "Productivity",
        bestFor: "Product Managers",
        shortDescription: "AI co-pilot for writing product requirements documents.",
        thumbnail: { url: images.business, alt: "Product requirements" },
        logoUrl: "/logos/chatprd.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.chatprd.ai",
        uses: ["PRD Writing", "Feature Specifying", "User Story Generation", "Product Strategy"],
        features: ["Templates", "AI Co-pilot", "Export to Notion/Jira", "Context Awareness"]
    },
    {
        id: "magic-patterns-hobby-1y",
        slug: "magic-patterns-hobby-1y",
        name: "Magic Patterns Hobby",
        duration: "1 year",
        priceInr: 499,
        category: "Design",
        bestFor: "UI Designers",
        shortDescription: "Generate UI components and patterns with AI.",
        thumbnail: { url: images.design, alt: "UI patterns" },
        logoUrl: "/logos/magic-patterns.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.magicpatterns.com",
        uses: ["UI Prototyping", "Component Generation", "Design Inspiration", "Frontend Code"],
        features: ["React/Tailwind Export", "Dark Mode Support", "Component Library", "AI Iteration"]
    },
    {
        id: "mobbin-pro-1y",
        slug: "mobbin-pro-1y",
        name: "Mobbin Pro",
        duration: "1 year",
        priceInr: 599,
        category: "Design",
        bestFor: "UX/UI Research",
        shortDescription: "Comprehensive library of mobile and web app screenshots.",
        thumbnail: { url: images.design, alt: "Mobile UI gallery" },
        logoUrl: "/logos/mobbin.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://mobbin.com",
        uses: ["UX Research", "Competitor Analysis", "Design Patterns", "Flow Visualization"],
        features: ["iOS/Android/Web Filters", "Flow Diagrams", "Copy Text", "Save Collections"]
    },
    {
        id: "elevenlabs-3m",
        slug: "elevenlabs-3m",
        name: "ElevenLabs",
        duration: "3 months",
        priceInr: 599,
        category: "AI Tools",
        bestFor: "Voiceovers and dubbing",
        shortDescription: "Generate realistic AI voiceovers in multiple languages.",
        thumbnail: { url: images.video, alt: "Audio waveform" },
        logoUrl: "/logos/elevenlabs.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://elevenlabs.io",
        uses: ["Audiobooks", "Video Dubbing", "Game Characters", "Accessibility"],
        features: ["Voice Cloning", "Text-to-Speech", "Multi-language", "Emotion Control"]
    },
    {
        id: "lumion-pro-1y",
        slug: "lumion-pro-1y",
        name: "Lumion Pro",
        duration: "1 year",
        priceInr: 1299,
        category: "Design",
        bestFor: "Architects",
        shortDescription: "Fast 3D rendering for architects and designers.",
        thumbnail: { url: images.design, alt: "Architectural render" },
        logoUrl: "/logos/lumion.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://lumion.com",
        uses: ["Architectural Visualization", "Landscape Design", "Interior Rendering", "Walkthroughs"],
        features: ["Real-time Rendering", "Content Library", "LiveSync", "Atmospheric Effects"]
    },
    {
        id: "jetbrains-1y",
        slug: "jetbrains-1y",
        name: "JetBrains",
        duration: "1 year",
        priceInr: 899,
        category: "Productivity",
        bestFor: "Developers",
        shortDescription: "Premium IDEs like IntelliJ, PyCharm and WebStorm.",
        thumbnail: { url: images.code, alt: "Code editor" },
        logoUrl: "/logos/jetbrains.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.jetbrains.com",
        uses: ["Software Development", "Code Analysis", "Refactoring", "Debugging"],
        features: ["IntelliJ IDEA", "PyCharm", "WebStorm", "Remote Development"]
    },
    {
        id: "make-1y",
        slug: "make-1y",
        name: "Make.com",
        duration: "1 year",
        priceInr: 849,
        category: "Business",
        bestFor: "Automation and workflows",
        shortDescription: "Automate apps and workflows with no‑code scenarios.",
        thumbnail: { url: images.business, alt: "Automation workflow" },
        logoUrl: "/logos/make.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.make.com",
        uses: ["Workflow Automation", "Data Sync", "App Integration", "Social Media Posting"],
        features: ["Visual Builder", "1000+ Apps", "Webhooks", "Error Handling"]
    },
    {
        id: "bolt-pro-1y",
        slug: "bolt-pro-1y",
        name: "Bolt Pro",
        duration: "1 year",
        priceInr: 399,
        category: "Productivity",
        bestFor: "Fast tasks",
        shortDescription: "Lightning fast task management and execution.",
        thumbnail: { url: images.productivity, alt: "Fast performance" },
        logoUrl: "/logos/bolt.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://bolt.new",
        uses: ["Task Management", "Quick Capture", "Daily Planning", "Focus Work"],
        features: ["Keyboard Shortcuts", "Natural Language", "Dark Mode", "Cross-platform"]
    },
    {
        id: "wispr-flow-pro-1y",
        slug: "wispr-flow-pro-1y",
        name: "Wispr Flow Pro",
        duration: "1 year",
        priceInr: 449,
        category: "Productivity",
        bestFor: "Voice dictation",
        shortDescription: "AI voice dictation that adapts to your style.",
        thumbnail: { url: images.productivity, alt: "Voice flow" },
        logoUrl: "/logos/wispr-flow.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.wispr.ai",
        uses: ["Dictation", "Note Taking", "Email Drafting", "Thought Capture"],
        features: ["Auto-formatting", "Style Adaptation", "Multi-language", "Instant Sync"]
    },
    {
        id: "devine-core-1y",
        slug: "devine-core-1y",
        name: "Devine Core",
        duration: "1 year",
        priceInr: 599,
        category: "AI Tools",
        bestFor: "Creative generation",
        shortDescription: "Advanced AI model for creative asset generation.",
        thumbnail: { url: images.ai, alt: "AI core" },
        logoUrl: "/logos/devine-core.jpg",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://devine.ai",
        uses: ["Asset Generation", "Concept Art", "Texture Creation", "Marketing Visuals"],
        features: ["High Resolution", "Style Control", "Batch Generation", "Commercial Rights"]
    },
    {
        id: "lovable-pro-1y",
        slug: "lovable-pro-1y",
        name: "Lovable Pro",
        duration: "1 year",
        priceInr: 499,
        category: "Design",
        bestFor: "Friendly interfaces",
        shortDescription: "Create lovable and friendly user interfaces.",
        thumbnail: { url: images.design, alt: "Friendly UI" },
        logoUrl: "/logos/lovable.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://lovable.dev",
        uses: ["UI Design", "Frontend Development", "Prototyping", "Design Systems"],
        features: ["AI Design Assistant", "Code Export", "Component Library", "Responsive Layouts"]
    },
    {
        id: "replit-core-1y",
        slug: "replit-core-1y",
        name: "Replit Core",
        duration: "1 year",
        priceInr: 599,
        category: "Productivity",
        bestFor: "Learning to code and hosting",
        shortDescription: "Online IDE with collaboration, hosting and AI tools.",
        thumbnail: { url: images.code, alt: "Cloud IDE" },
        logoUrl: "/logos/replit.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://replit.com",
        uses: ["Coding in Browser", "Hosting Apps", "Collaborative Coding", "Learning Python/JS"],
        features: ["Ghostwriter AI", "Private Repls", "Always-on Boosts", "Multiplayer Editing"]
    },
    {
        id: "n8n-cloud-starter-1y",
        slug: "n8n-cloud-starter-1y",
        name: "n8n Cloud Starter",
        duration: "1 year",
        priceInr: 799,
        category: "Business",
        bestFor: "Custom automations",
        shortDescription: "Flexible workflow automation with self‑host style logic.",
        thumbnail: { url: images.business, alt: "Workflow automation" },
        logoUrl: "/logos/n8n.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://n8n.io",
        uses: ["Complex Automations", "Data Processing", "API Integration", "Self-hosted Logic"],
        features: ["Workflow Editor", "JavaScript Functions", "200+ Nodes", "Execution Log"]
    },
    {
        id: "descript-creator-1y",
        slug: "descript-creator-1y",
        name: "Descript Creator",
        duration: "1 year",
        priceInr: 649,
        category: "Video",
        bestFor: "Podcasts and video edits",
        shortDescription: "Edit audio and video by editing text like a doc.",
        thumbnail: { url: images.video, alt: "Video editing" },
        logoUrl: "/logos/descript.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.descript.com",
        uses: ["Podcast Editing", "Video Transcription", "Screen Recording", "Social Clips"],
        features: ["Overdub", "Studio Sound", "Text-based Editing", "Filler Word Removal"]
    },
    {
        id: "warp-pro-1y",
        slug: "warp-pro-1y",
        name: "Warp Pro",
        duration: "1 year",
        priceInr: 399,
        category: "Productivity",
        bestFor: "Developers",
        shortDescription: "The terminal for the 21st century.",
        thumbnail: { url: images.code, alt: "Modern terminal" },
        logoUrl: "/logos/warp.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.warp.dev",
        uses: ["Command Line", "DevOps", "Scripting", "Server Management"],
        features: ["AI Command Search", "Shared Workflows", "Block-based Output", "Themes"]
    },
    {
        id: "gamma-pro-1y",
        slug: "gamma-pro-1y",
        name: "Gamma Pro",
        duration: "1 year",
        priceInr: 499,
        category: "AI Tools",
        bestFor: "Decks and docs",
        shortDescription: "AI‑generated slides, docs and webpages for ideas.",
        thumbnail: { url: images.ai, alt: "AI slides" },
        logoUrl: "/logos/gamma.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://gamma.app",
        uses: ["Presentation Decks", "Documents", "Webpages", "Client Proposals"],
        features: ["One-click Polish", "Embed Content", "Analytics", "PDF Export"]
    },
    {
        id: "picsart-pro-1y",
        slug: "picsart-pro-1y",
        name: "PicsArt Pro",
        duration: "1 year",
        priceInr: 349,
        category: "Design",
        bestFor: "Mobile editing",
        shortDescription: "All-in-one photo and video editor.",
        thumbnail: { url: images.design, alt: "Photo editing" },
        logoUrl: "/logos/picsart.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://picsart.com",
        uses: ["Photo Editing", "Collage Making", "Social Media Graphics", "Video Editing"],
        features: ["Background Remover", "AI Image Gen", "Premium Fonts", "Templates"]
    },
    {
        id: "grammarly-pro-1y",
        slug: "grammarly-pro-1y",
        name: "Grammarly Pro",
        duration: "1 year",
        priceInr: 599,
        category: "Productivity",
        bestFor: "Writers and professionals",
        shortDescription: "Fix grammar, tone and clarity across your writing.",
        thumbnail: { url: images.productivity, alt: "Writing assistant" },
        logoUrl: "/logos/grammarly.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.grammarly.com",
        uses: ["Proofreading", "Tone Adjustment", "Plagiarism Check", "Email Writing"],
        features: ["Advanced Suggestions", "Rewrite for Clarity", "Style Guide", "Snippet Library"]
    },
    {
        id: "freepik-premium-1y",
        slug: "freepik-premium-1y",
        name: "Freepik Premium",
        duration: "1 year",
        priceInr: 699,
        category: "Design",
        bestFor: "Designers and marketers",
        shortDescription: "Access premium vectors, photos, PSDs and icons.",
        thumbnail: { url: images.design, alt: "Vector assets" },
        logoUrl: "/logos/freepik.png",
        canUseInAppUI: true,
        brandNotes: "Official logo uploaded by user.",
        officialWebsite: "https://www.freepik.com",
        uses: ["Graphic Design", "Marketing Materials", "Web Design", "Social Media"],
        features: ["Vectors & PSDs", "Stock Photos", "No Attribution", "Daily Downloads"]
    },
    {
        id: "envato-elements-1y",
        slug: "envato-elements-1y",
        name: "Envato Elements",
        duration: "1 year",
        priceInr: 1499,
        category: "Design",
        bestFor: "Agencies and content creators",
        shortDescription: "Unlimited creative assets: templates, stock and more.",
        thumbnail: { url: images.design, alt: "Creative assets" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Web Design", "Video Production", "Graphic Design", "Audio Production"],
        features: ["Unlimited Downloads", "Stock Video & Audio", "WordPress Themes", "3D Objects"]
    },
    {
        id: "flutterflow-1y",
        slug: "flutterflow-1y",
        name: "FlutterFlow",
        duration: "1 year",
        priceInr: 899,
        category: "Productivity",
        bestFor: "App builders",
        shortDescription: "Build Flutter apps visually without deep coding.",
        thumbnail: { url: images.code, alt: "App builder" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Mobile App Dev", "Prototyping", "MVP Building", "Cross-platform Apps"],
        features: ["Visual Builder", "Firebase Integration", "Code Export", "Custom Actions"]
    },
    {
        id: "adobe-express-1y",
        slug: "adobe-express-1y",
        name: "Adobe Express",
        duration: "1 year",
        priceInr: 399,
        category: "Design",
        bestFor: "Quick social media designs",
        shortDescription: "Create quick graphics, posts and short videos easily.",
        thumbnail: { url: images.design, alt: "Social media design" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Social Media Posts", "Flyers & Posters", "Basic Video Editing", "Logo Design"],
        features: ["Thousands of Templates", "Adobe Stock Photos", "Remove Background", "Brand Kits"]
    },
    {
        id: "wedflow-1y",
        slug: "wedflow-1y",
        name: "Wedflow",
        duration: "1 year",
        priceInr: 499,
        category: "Design",
        bestFor: "Wedding Planners",
        shortDescription: "Wedding planning and design software.",
        thumbnail: { url: images.design, alt: "Wedding planning" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Wedding Planning", "Guest Management", "Vendor Coordination", "Budget Tracking"],
        features: ["Timeline Builder", "Seating Charts", "RSVP Tracking", "Collaboration Tools"]
    },
    {
        id: "edx-enterprises-1y",
        slug: "edx-enterprises-1y",
        name: "edX Enterprises",
        duration: "1 year",
        priceInr: 999,
        category: "Learning",
        bestFor: "Corporate training",
        shortDescription: "Enterprise-grade learning for teams.",
        thumbnail: { url: images.learning, alt: "Enterprise learning" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Employee Training", "Skill Development", "Leadership Training", "Compliance"],
        features: ["Top University Courses", "Analytics Dashboard", "Custom Learning Paths", "Certificates"]
    },
    {
        id: "invideo-studio-3y",
        slug: "invideo-studio-3y",
        name: "InVideo Studio",
        duration: "3 years",
        priceInr: 1299,
        category: "Video",
        bestFor: "YouTubers and marketers",
        shortDescription: "Template‑based video creation for social and ads.",
        thumbnail: { url: images.video, alt: "Video templates" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Promo Videos", "Social Media Ads", "YouTube Intros", "Video Presentations"],
        features: ["5000+ Templates", "Stock Media Library", "Text-to-Video", "Voiceovers"]
    },
    {
        id: "capcut-pro-6m",
        slug: "capcut-pro-6m",
        name: "CapCut Pro",
        duration: "6 months",
        priceInr: 499,
        category: "Video",
        bestFor: "Short‑form editors",
        shortDescription: "Advanced tools for Reels, Shorts and TikToks.",
        thumbnail: { url: images.video, alt: "Mobile video editor" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["TikTok/Reels Editing", "Vlogging", "Video Effects", "Color Grading"],
        features: ["Keyframe Animation", "Auto Captions", "Background Removal", "Trending Effects"]
    },
    {
        id: "linkedin-career-3m",
        slug: "linkedin-career-3m",
        name: "LinkedIn Career",
        duration: "3 months",
        priceInr: 399,
        category: "Business",
        bestFor: "Job seekers",
        shortDescription: "See who viewed your profile and unlock job insights.",
        thumbnail: { url: images.business, alt: "Career insights" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Job Hunting", "Networking", "Skill Building", "Salary Research"],
        features: ["InMail Credits", "Who Viewed Your Profile", "Applicant Insights", "Learning Courses"]
    },
    {
        id: "linkedin-business-3m",
        slug: "linkedin-business-3m",
        name: "LinkedIn Business",
        duration: "3 months",
        priceInr: 649,
        category: "Business",
        bestFor: "Freelancers and agencies",
        shortDescription: "Grow your network and reach with business tools.",
        thumbnail: { url: images.business, alt: "Business networking" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Lead Generation", "Talent Scouting", "Business Insights", "Company Research"],
        features: ["Unlimited People Browsing", "Business Insights", "15 InMails/mo", "Online Video Courses"]
    },
    {
        id: "linkedin-ads-10k",
        slug: "linkedin-ads-10k",
        name: "LinkedIn Ads Credit",
        duration: "10k Credit",
        priceInr: 2999,
        category: "Business",
        bestFor: "Marketers",
        shortDescription: "Ad credits to boost your LinkedIn campaigns.",
        thumbnail: { url: images.business, alt: "Ad analytics" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["B2B Marketing", "Brand Awareness", "Lead Gen Campaigns", "Recruitment Ads"],
        features: ["Sponsored Content", "Message Ads", "Audience Targeting", "Conversion Tracking"]
    },
    {
        id: "canva-pro-1m",
        slug: "canva-pro-1m",
        name: "Canva Pro",
        duration: "1 month",
        priceInr: 149,
        category: "Design",
        bestFor: "Non‑designers and small teams",
        shortDescription: "Drag‑and‑drop design tool with premium templates.",
        thumbnail: { url: images.design, alt: "Design templates" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Graphic Design", "Presentations", "Social Media Content", "Print Materials"],
        features: ["Brand Kit", "Magic Resize", "Background Remover", "Premium Content"]
    },
    {
        id: "filmora-pro-lifetime",
        slug: "filmora-pro-lifetime",
        name: "Filmora Pro",
        duration: "Lifetime",
        priceInr: 1049,
        category: "Video",
        bestFor: "Editors who want a one‑time purchase",
        shortDescription: "Video editing with a lifetime license, no renewal.",
        thumbnail: { url: images.video, alt: "Video editor timeline" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["YouTube Videos", "Tutorials", "Vlogs", "Short Films"],
        features: ["Advanced Color Tuning", "Audio Ducking", "Motion Tracking", "Split Screen"]
    },
    {
        id: "pngtree-lifetime",
        slug: "pngtree-lifetime",
        name: "Pngtree",
        duration: "Lifetime",
        priceInr: 599,
        category: "Design",
        bestFor: "Graphic Designers",
        shortDescription: "Millions of PNG images, backgrounds and vectors.",
        thumbnail: { url: images.design, alt: "PNG assets" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Graphic Design", "Web Banners", "Presentations", "Marketing Art"],
        features: ["Millions of PNGs", "Vectors & PSDs", "Backgrounds", "Commercial License"]
    },
    {
        id: "pikbest-lifetime",
        slug: "pikbest-lifetime",
        name: "Pikbest",
        duration: "Lifetime",
        priceInr: 599,
        category: "Design",
        bestFor: "Presenters",
        shortDescription: "Templates for presentations, posters and more.",
        thumbnail: { url: images.design, alt: "Presentation templates" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Poster Design", "PowerPoint Templates", "Sound Effects", "Video Templates"],
        features: ["Daily Updates", "Commercial Usage", "Source Files", "Multi-category"]
    },
    {
        id: "microsoft-office-365-lifetime",
        slug: "microsoft-office-365-lifetime",
        name: "Microsoft Office 365",
        duration: "Lifetime",
        priceInr: 399,
        category: "Productivity",
        bestFor: "Students and professionals",
        shortDescription: "Word, Excel, PowerPoint and more in one license.",
        thumbnail: { url: images.productivity, alt: "Office suite" },
        logoUrl: null,
        canUseInAppUI: false,
        uses: ["Document Creation", "Spreadsheets", "Presentations", "Email & Calendar"],
        features: ["Word, Excel, PPT", "1TB OneDrive", "Outlook", "Teams"]
    }
];

export const plans = products.map((product) => ({
    id: product.id,
    name: product.name,
    duration: product.duration,
    priceDisplay: `₹${product.priceInr}/-`,
    logo: product.logoUrl || product.thumbnail.url,
}));
